current_config = "instance_wdf"

[configurations.default]
serial_number = "1"
absolute_serial_number = 1
version_path = "0.0.0"
nickname_path = "默认配置"
mai_path = ""
adapter_path = ""
napcat_path = ""
qq_account = ""

[configurations.try]
serial_number = "try"
qq_account = "10086"
absolute_serial_number = 2
version_path = "0.10.0"
nickname_path = "try"
mai_path = "D:\\MaiMbot\\test\\test\\MaiBot"
adapter_path = "适配器路径验证失败"
napcat_path = "D:/NapCat\\NapCat.Framework.Windows.OneKey\\bootmain\\NapCatWinBootMain.exe"
mongodb_path = ""
webui_path = ""

[configurations.test]
serial_number = "test"
qq_account = "123456"
absolute_serial_number = 3
version_path = "0.10.0"
nickname_path = "test"
mai_path = "D:\\MaiMbot\\test\\test\\MaiBot"
adapter_path = "D:\\MaiMbot\\test\\test\\MaiBot\\adapter"
napcat_path = "D:\\MaiMbot\\test\\test\\NapCat\\NapCat.34740.Shell\\NapCatWinBootMain.exe"
mongodb_path = ""
webui_path = ""

[configurations.abc]
serial_number = "abc"
qq_account = "13579"
absolute_serial_number = 4
version_path = "0.10.0"
nickname_path = "abc"
mai_path = "D:\\MaiMbot\\test\\test\\MaiBot"
adapter_path = "D:\\MaiMbot\\test\\test\\MaiBot\\adapter"
napcat_path = "D:\\MaiMbot\\test\\test\\NapCat\\NapCat.34740.Shell\\NapCatWinBootMain.exe"
mongodb_path = ""
webui_path = ""

[configurations.instance_wdf]
serial_number = "wdf"
absolute_serial_number = 5
version_path = "0.9.0-alpha"
nickname_path = "wdf"
qq_account = "0987654321"
mai_path = "D:\\MaiMbot\\test\\wdf\\MaiBot"
adapter_path = "D:\\MaiMbot\\test\\wdf\\MaiBot\\adapter"
napcat_path = "D:\\MaiMbot\\test\\wdf\\NapCat\\NapCat.34740.Framework\\NapCatWinBootMain.exe"
venv_path = "D:\\MaiMbot\\test\\wdf\\MaiBot\\venv"
mongodb_path = ""
webui_path = ""

[configurations.try.install_options]
install_adapter = true
install_napcat = true
install_mongodb = false
install_webui = false

[configurations.test.install_options]
install_adapter = true
install_napcat = true
install_mongodb = false
install_webui = false

[configurations.abc.install_options]
install_adapter = true
install_napcat = true
install_mongodb = false
install_webui = false

[configurations.instance_wdf.install_options]
install_adapter = true
install_napcat = true
install_mongodb = false
install_webui = false
