current_config = "instance_101465"

[configurations.default]
serial_number = "1"
absolute_serial_number = 1
version_path = "0.0.0"
nickname_path = "默认配置"
mai_path = ""
adapter_path = ""
napcat_path = ""

[configurations.instance_114514]
serial_number = "114514"
absolute_serial_number = 2
version_path = "0.8.1-alpha"
nickname_path = "114514"
mai_path = "E:\\delveoper\\maimai-luncher\\test\\MaiBot"
adapter_path = "E:\\delveoper\\maimai-luncher\\test\\MaiBot\\adapter"
napcat_path = "E:\\delveoper\\maimai-luncher\\test\\NapCat\\NapCat.34740.Shell\\NapCatWinBootMain.exe"
venv_path = "E:\\delveoper\\maimai-luncher\\test\\MaiBot\\venv"
mongodb_path = ""
webui_path = "E:\\delveoper\\maimai-luncher\\test\\WebUI"

[configurations.instance_101465]
serial_number = "101465"
absolute_serial_number = 3
version_path = "0.6.2-alpha"
nickname_path = "114514"
mai_path = "E:\\delveoper\\maimai-luncher\\0.6.2\\MaiBot"
adapter_path = "E:\\delveoper\\maimai-luncher\\0.6.2\\MaiBot\\adapter"
napcat_path = "E:\\delveoper\\maimai-luncher\\0.6.2\\NapCat\\NapCat.34740.Shell\\NapCatWinBootMain.exe"
venv_path = "E:\\delveoper\\maimai-luncher\\0.6.2\\MaiBot\\venv"
mongodb_path = "E:\\delveoper\\maimai-luncher\\0.6.2\\mongodb"
webui_path = "E:\\delveoper\\maimai-luncher\\0.6.2\\WebUI"

[configurations.instance_114514.install_options]
install_adapter = true
install_napcat = true
install_mongodb = false
install_webui = true

[configurations.instance_101465.install_options]
install_adapter = true
install_napcat = true
install_mongodb = true
install_webui = true
